USE actividades;

-- 3.1
SELECT * 
FROM almacenes;

-- 3.2 
SELECT * 
FROM cajas
WHERE valor > 150;

-- 3.3
SELECT DISTINCT CONTENIDO
FROM cajas;

-- 3.4
SELECT AVG(valor)
FROM cajas;

-- 3.5
SELECT ALMACEN, AVG(VALOR)
FROM cajas
GROUP BY ALMACEN;

-- 3.6
SELECT ALMACEN
FROM cajas
GROUP BY ALMACEN
HAVING AVG(VALOR) > 150;

-- 3.7
SELECT c.NUMREFERENCIA, a.LUGAR
FROM cajas c
JOIN almacenes a ON c.ALMACEN = a.CODIGO;

-- 3.8
SELECT ALMACEN, COUNT(*) AS NumeroDeCajas
FROM cajas
GROUP BY ALMACEN;

-- 3.9
SELECT ALMACEN
FROM cajas
GROUP BY ALMACEN
HAVING COUNT(*) > (
	SELECT CAPACIDAD 
	FROM almacenes 
	WHERE CODIGO = cajas.ALMACEN);
    
-- 3.10
SELECT NUMREFERENCIA
FROM cajas
WHERE ALMACEN = 3;

-- 3.11
INSERT INTO almacenes (CODIGO, LUGAR, CAPACIDAD) VALUES (6, 'Barcelona', 3);

-- 3.12
INSERT INTO cajas (NUMREFERENCIA, CONTENIDO, VALOR, ALMACEN) VALUES ('H5RT', 'Papel', 200, 2);

-- 3.13
SET SQL_SAFE_UPDATES = 0;
UPDATE cajas SET VALOR = VALOR * 0.85;

-- 3.14
UPDATE cajas SET VALOR = VALOR * 0.8 WHERE VALOR > (SELECT AVG(VALOR) FROM cajas);

-- 3.15
DELETE FROM cajas WHERE VALOR < 100;

-- 3.16
DELETE FROM cajas
WHERE ALMACEN IN (
    SELECT almacenes.CODIGO
    FROM almacenes
    WHERE almacenes.CAPACIDAD < (SELECT COUNT(*) FROM cajas WHERE ALMACEN = almacenes.CODIGO)
);







